// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmZtVNkCcGlgXUM08uOjnqALEx3y6AIL8',
    appId: '1:620561442809:web:cac7028eed9dfb9c7eff28',
    messagingSenderId: '620561442809',
    projectId: 'vibeng-34731',
    authDomain: 'vibeng-34731.firebaseapp.com',
    storageBucket: 'vibeng-34731.firebasestorage.app',
    measurementId: 'G-0N2T8S4X2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC12kt6Vw2ewj3lSKWyTGrVFx9NX76ri8A',
    appId: '1:620561442809:android:497a61e6bad561b47eff28',
    messagingSenderId: '620561442809',
    projectId: 'vibeng-34731',
    storageBucket: 'vibeng-34731.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdG-IfSjTGFlThYUDbbSGisjw3OvcubQ4',
    appId: '1:620561442809:ios:cf50a33952841fb87eff28',
    messagingSenderId: '620561442809',
    projectId: 'vibeng-34731',
    storageBucket: 'vibeng-34731.firebasestorage.app',
    iosBundleId: 'com.example.vibeng',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdG-IfSjTGFlThYUDbbSGisjw3OvcubQ4',
    appId: '1:620561442809:ios:cf50a33952841fb87eff28',
    messagingSenderId: '620561442809',
    projectId: 'vibeng-34731',
    storageBucket: 'vibeng-34731.firebasestorage.app',
    iosBundleId: 'com.example.vibeng',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmZtVNkCcGlgXUM08uOjnqALEx3y6AIL8',
    appId: '1:620561442809:web:4fb254c0e2d6c8347eff28',
    messagingSenderId: '620561442809',
    projectId: 'vibeng-34731',
    authDomain: 'vibeng-34731.firebaseapp.com',
    storageBucket: 'vibeng-34731.firebasestorage.app',
    measurementId: 'G-9MREB99X20',
  );
}
